### ISSUE TITLE
Adapt Photo Picker to maximize WPAndroid's picker reuse

### ISSUE THREAD

**Issue by mzorz** [Automattic/stories-android#244]
**UPDATE**

This is the latest approach
![image](https://user-images.githubusercontent.com/6597771/82252717-e7cc7f80-9925-11ea-9890-d9c4fc73a108.png)

=====================================
old description

**Note: This issue is better tackled if / when we integrate the Story creation flow to WPAndroid.**

In order to minimize the integration effort (when we potentially integrate the Story creation flow to WPAndroid) and try to reuse the existing WPAndroid picker as much as possible, we could align to a mix of how Gutenberg shows things, with a recent media preview (but occupying the full screen instead of the half-screen shown in Aztec). (The "recent media" list would be as currently shown in Portkey fwiw)

This way, we'd have something like this:

<img width="853" alt="Screen Shot 2020-01-08 at 16 08 08" src="https://user-images.githubusercontent.com/6597771/72007746-1ed0ad00-3231-11ea-8f9f-b9abc8679663.png">

The options for media picker's top drop down filter would be:
- Choose from device (this triggers the device's standard media picker, as usual)
- WordPress Media Library
- Choose from Free Photo Library
_(Take a photo would not be here, as there's the dedicated FAB for such action)_

#### ToDo
For now, we've only made some basic adjustments to comply with the design in https://github.com/Automattic/portkey-android/pull/243, and can either fully implement the rest of the functionality or make that part of the integration, this being:
- [ ] reuse styles / themes from host project
- [ ] Change top filter to include the options outlined above:
    - Choose from device (this triggers the device's standard media picker, as usual)
    - WordPress Media Library
    - Choose from Free Photo Library
- [ ] Adapt the description text "Choose the photos..." and FAB into the WPAndroid picker
