### ISSUE TITLE
WP integration checklist

### ISSUE THREAD

**Issue by mzorz** [Automattic/stories-android#249]
#### Alpha phase 1
Alpha phase 1 is an internal release of a feature branch build, probably make use of jalapeno for that.
- [x] FrameSaveService event snackbars on main screen (see #336 and https://github.com/wordpress-mobile/WordPress-Android/pull/11931)
- [x] fluxC integration https://github.com/Automattic/portkey-android/issues/195 (remember to look into `showProvidedMediaPicker()` in StoryComposerActivity to pass the local Post id or decide what to do with that)) _NOTE: we ended up using a different architecture integrating at the media file level instead of encapsulating a shared MediaModel. The Stories library is WP-agnostic this way._
- [x] media picker integration #244
- [x] add EmojiCompat initialization to WordPress https://github.com/wordpress-mobile/WordPress-Android/pull/12045
- [x] ~model wrapping TBD (also only create a Gallery block with images for now - no new GB block introduced at this phase)~ decided to keep it lightweight: there's little to a Story post that is distinguishable from a regular post. May use a wrapper as a handy convention but nothing fancy.
- [x] ~remember to check use of WPAndroid's `SingleLiveEvent` instead of our copy in MVVM (should we use ours? we need to keep Portkey app functional)~  -decided to leave our copy in the stories app to avoid dependency
- [x] Upload Service integration #267 
- [x] ~Upload notifications integration #268~
- [x] Bottom sheet #194 
~- [ ] List of stories https://github.com/Automattic/portkey-android/issues/269~
- [x] add Tracks tracking. 
1. Look for all TODOs added.  (i.e. `// TODO WPSTORIES add TRACKS`)
2. Also look on Post creation track events (follow `trackEditorCreatedPost()` in EditPostActivity) 
3. check session behavior introduced in https://github.com/wordpress-mobile/WordPress-Android/pull/9293
~- [ ] remember to add `wp.stories.use.cameraX = true` to `gradle.properties-example` and secrets repo~ added `use.camerax.` per default

#### merge to develop
- [x] make the portkey-android repo public **HEADS UP Lorenzo / platform9 before merging to develop** (_"gave some additional rights on the whole portkey-android project parent organization to the wpmobilebot that we may want to remove if they are not required"_)
- [x] Also ask platform9 about string translation, do we need anything special? remember to bring this up https://github.com/wordpress-mobile/WordPress-Android/pull/11930#discussion_r435077926
- [x] merge to develop

#### internal Beta 1
This collects issues discovered in alpha phase 1, adds unit tests, refactors, etc and prepares for an actual WPAndroid alpha in their release cycle
- [x] move code from StoryComposerActivity to ViewModel as suggested by @malinajirka in https://github.com/wordpress-mobile/WordPress-Android/pull/11953
~- [ ] check if we want to use the ImageEditor path when picking images from the media picker (see https://github.com/wordpress-mobile/WordPress-Android/pull/11939#issuecomment-639425245)~  checked in with Megs, decided this is more of an enhancement used in story slide editing but we shouldn't add another step to story creation itself
- [x] See #443 -  check styles and apply WP's styles to all items (check alert dialog button style hacks for example - see style applied in #247). This should include work to make  dark mode support work well (see https://github.com/wordpress-mobile/WordPress-Android/labels/Dark%20Mode)
- [ ] check updating CameraX library at this point? #272
- [x] add more unit tests
- [x] test TABLETS
- [x] Release: remember to use release notes priority indicators `priority-indicators-for-release-notes/` (`[***]`)
- [x] turn feature flag off. Remember to update to user remote flag in case we need it.
- [ ] TBD

#### Beta
This collects issues discovered in alpha phases 1 & 2, adds more unit tests, refactors, etc
- [ ] check updating CameraX library if a new version is available (same with other libraries)
- [x] add more unit tests
- [x] text enhancements
- [ ] posts list enhancements
- [ ] add stickers (emoji, gif, date, time, location.) See #191 and #190. Also add more emoji (we have a limited set only now)
- [x] implement the proper Story block in mobile Gutenberg https://github.com/Automattic/stories-android/issues/504
- [x] implement **Onboarding** flows
- [x] update `LicensesActivity` `"file:///android_asset/licenses.html"`  to include libraries licenses
- [ ] TBD

**Comment by mzorz** [comment]
Closing this one, Stories has been released with [version 16.3 of WPAndroid](https://github.com/wordpress-mobile/WordPress-Android/releases/tag/16.3) - everything else is already integrated and whatever is important for the Stories project is being tracked elsewhere already
