### ISSUE TITLE
Text enhancements - primary thread

### ISSUE THREAD

**Issue by mzorz** [Automattic/stories-android#274]
- [x] Support text alignment #186
- [x] Support changing fonts #185
- [x] Set background / foreground color for text #170
- [x] Enhanced color picker #465 
- [x] Color picker button coloring (worthy of a separate PR) --> #603 
- [x] Text size slider (improves #532)
- [x] Do a final sweep to verify dark mode support is in good shape (especially for the color picker bottom sheet)
- [x] Design review pass

![text-editing-colors-1](https://user-images.githubusercontent.com/9613966/88614197-30dd4480-d0ca-11ea-8e72-7c39f5a73684.png)

**Comment by aforcier** [comment]
All done! 🎉
