### ISSUE TITLE
Bottom sheet issues

### ISSUE THREAD

**Issue by mzorz** [Automattic/stories-android#419]
Listing the bottom sheet issues here:

> Status & Visibility defaulted to Draft?

Should be PUBLISHED by default

>  The tags interface was not very intuitive 

> - I got an uploading null message when I tried to publish the story (it had no name)...

This `null` we shoud use the `Untitled` placeholder that was stripped before.

>  in the pre-publish sheet, I tapped on “Status & visibility” and I changed it to “Publish”. The post wasn’t published, but the button in the pre-publish sheet changed from “Publish now” to “Update now”, which was confusing.

> The Story title didn’t appear to work; anything I entered would disappear upon navigating away from the pre-publish sheet (like choosing tags). This was unexpected even though I saw above that the story would be uploaded without a title.

> In the pre-publish sheet, there wasn’t a clear way to move forward after typing a title; the return button didn’t seem to do anything and I had to minimize the keyboard manually to find the publish button.

> The publish button was obscured so that only the top ~10px were tappable, and I couldn’t swipe up on the sheet to make it visible.
-------------------

- [x] Bottom sheet back pressed - tap twice issue https://github.com/wordpress-mobile/WordPress-Android/issues/12406
- [x] Story title layout not focusing input control https://github.com/wordpress-mobile/WordPress-Android/issues/12407
- [x] Capitalize story title text https://github.com/wordpress-mobile/WordPress-Android/issues/12408
- [x] Cursor stops blinking after typing https://github.com/wordpress-mobile/WordPress-Android/issues/12411
